on: [workflow_call]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: Run Commisery
      uses: tomtom-international/commisery-action@master
      with:
        token: ${{ github.token }}
        # don't validate the pull request title
        validate-pull-request: false
        validate-pull-request-title-bump: false
